PROVIDERS = [
    {
        "id": "runpod-a100-us-east",
        "name": "RunPod · A100 US-East",
        "region": "us-east-1",
        "gpu_type": "NVIDIA A100 80GB",
        "price_per_hour": 2.49,
        "uptime_pct": 99.8,
        "status": "available",
    },
    {
        "id": "runpod-3090-eu-west",
        "name": "RunPod · RTX 3090 EU-West",
        "region": "eu-west-1",
        "gpu_type": "NVIDIA RTX 3090",
        "price_per_hour": 0.69,
        "uptime_pct": 99.2,
        "status": "available",
    },
    {
        "id": "runpod-a6000-eu-central",
        "name": "RunPod · A6000 EU-Central",
        "region": "eu-central-1",
        "gpu_type": "NVIDIA RTX A6000",
        "price_per_hour": 1.34,
        "uptime_pct": 99.9,
        "status": "busy",
    },
    {
        "id": "vastai-h100-us-west",
        "name": "Vast.ai · H100 US-West",
        "region": "us-west-2",
        "gpu_type": "NVIDIA H100 SXM5",
        "price_per_hour": 3.15,
        "uptime_pct": 98.5,
        "status": "busy",
    },
    {
        "id": "vastai-4090-us-central",
        "name": "Vast.ai · RTX 4090 US-Central",
        "region": "us-central-1",
        "gpu_type": "NVIDIA RTX 4090",
        "price_per_hour": 0.94,
        "uptime_pct": 97.1,
        "status": "available",
    },
    {
        "id": "vastai-a40-ap-southeast",
        "name": "Vast.ai · A40 AP-Southeast",
        "region": "ap-southeast-1",
        "gpu_type": "NVIDIA A40",
        "price_per_hour": 1.12,
        "uptime_pct": 98.9,
        "status": "available",
    },
    {
        "id": "colo-v100-us-east",
        "name": "Colo · V100 US-East",
        "region": "us-east-2",
        "gpu_type": "NVIDIA V100 32GB",
        "price_per_hour": 0.55,
        "uptime_pct": 99.5,
        "status": "available",
    },
    {
        "id": "colo-3080ti-us-west",
        "name": "Colo · RTX 3080 Ti US-West",
        "region": "us-west-1",
        "gpu_type": "NVIDIA RTX 3080 Ti",
        "price_per_hour": 0.42,
        "uptime_pct": 98.1,
        "status": "available",
    },
]
